version: "3"
services:

  # APP*****************************************
  ULearn_registerLogin_ms:
    build: app/
    image: springbootapp:latest
    network_mode: bridge
    container_name: ULearn_registerLogin_ms
    expose:
      - 6665
    ports:
      - 6665:6665
    restart: unless-stopped
volumes:
  postgres-data: